# Generated by Django 3.2.13 on 2022-05-31 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=250)),
                ('description', models.TextField(max_length=10000)),
                ('color', models.CharField(max_length=50)),
                ('engine_power', models.IntegerField()),
                ('engine_power_unit', models.CharField(choices=[('KM', 'Konie Mechaniczne'), ('KW', 'Kilowaty')], max_length=150)),
                ('engine_capacity', models.IntegerField()),
                ('type_body', models.CharField(choices=[('SEDAN', 'SEDAN'), ('HATCHBACK', 'HATCHBACK'), ('KOMBI', 'KOMBI')], max_length=150)),
                ('production_year', models.IntegerField()),
                ('mileage', models.IntegerField()),
                ('mileage_type', models.CharField(choices=[('km', 'KILOMETRY'), ('mile', 'MILE')], max_length=150)),
                ('petrol_type', models.CharField(choices=[('ELECTRIC', 'ELEKTRTYCZY'), ('PETROL', 'BENZYNA'), ('HYBRID', 'HYBRYDOWY'), ('DIESEL', 'DIESEL'), ('LPG', 'LPG'), ('CNG', 'CNG')], max_length=150)),
            ],
        ),
    ]
