# Generated by Django 3.2.13 on 2022-06-21 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_auction_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='end_date',
            field=models.DateTimeField(verbose_name='Koniec aukcji'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='photo',
            field=models.ImageField(null=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='auction',
            name='start_date',
            field=models.DateTimeField(verbose_name='Początek aukcji'),
        ),
    ]
